title: Sector efe
tagline: "A programmer's portfolio and blog"
email: rod@sector-efe.net
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Rod* Wilhelmy A.K.A. defvol (formerly rodowi).
  Here you'll find my portfolio and some technical blog posts.
  Hope you enjoy it.
  Peace.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sector-efe.net"
twitter_username: defvol
github_username:  defvol

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Lanyon setup
permalink: pretty
paginate: 5

# About/contact
author:
  name:              Rod Wilhelmy
  email:             rod@sector-efe.net

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
