title: Sector efe
email: rod@sector-efe.net
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Rod* Wilhelmy A.K.A. defvol (formerly rodowi).
  Here you'll find my portfolio and some technical blog posts.
  Hope you enjoy it.
  Peace.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: defvol
github_username:  defvol

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
